
- name: get facts
  setup:
    gather_subset: hardware

- name: set memory
  set_fact:
    _innodb_buffer_pool_size: "{{(ansible_memtotal_mb * 0.6 // 1024 )| round |int }}G"

- debug:
    msg: "_innodb_buffer_pool_size: {{_innodb_buffer_pool_size}}"

- name: get ip
  shell: echo {{ ansible_all_ipv4_addresses[0] }}  |awk -F. '{printf("%03d\n",$3)}'
  register: ip_st


- name: get ip1
  shell: echo {{ ansible_all_ipv4_addresses[0] }}  |awk -F. '{printf("%03d\n",$4)}'
  register: ip_st1

- name: set ip
  set_fact:
    _server_id: "{{ MYSQL_PORT}}{{ ip_st.stdout }}{{ ip_st1.stdout }}"


