# 确认当前主机磁盘信息
# 确认主机是否有mysql服务
- name: check mysql service exits
  shell: ps -ef|grep {{MYSQL_PORT}} |grep "mysqld"|grep -v "grep"|wc -l
  register: check_mysqld_value

- name: if mysql {{MYSQL_PORT}} service is exists
  fail: msg="mysql and  {{MYSQL_PORT}} service is exists,please check now!!!"
  when: check_mysqld_value.stdout|int > 0

# 创建账号和用户
- name: create mysql user
  user: name={{MYSQL_USER}}  group={{MYSQL_USER}} state=present create_home=True

# 拷贝mysql-packaga到目标主机
- name: create tmp dir
  file: name=/tmp/mysql/mysql{{ MYSQL_PORT }} state=directory owner={{MYSQL_USER}} group={{MYSQL_USER}} mode=0750  recurse=yes

- name: mysql unarchive dir is not exists
  shell: ls /tmp/mysql/mysql{{ MYSQL_PORT }}|grep {{ MYSQL_VERSION }}|wc -l
  register: unarchive_num

- name: unarchive mysql_package
  unarchive: src={{ item }} dest=/tmp/mysql creates={{MYSQL_USER}} copy=yes  group={{MYSQL_USER}}
  with_fileglob:
  - "{{ MYSQL_VERSION }}*"
  when: not unarchive_num.stdout|int > 0
- name: mysql base dir is not exists
  stat: path={{ BASE_DIR }}
  register: base_ok
- name: rename mysql_dir
  shell: "cp -r  /tmp/mysql/`ls /tmp/mysql |grep {{ MYSQL_VERSION }}`  {{BASE_DIR}}/;chown -R {{MYSQL_USER}}:{{MYSQL_USER}} {{BASE_DIR}}/"
  when: not base_ok.stat.exists

- name: create dir for mysql
  file: name={{ item }} state=directory owner={{MYSQL_USER}} group={{MYSQL_USER}} mode=0750  recurse=yes
  with_items:
  - "{{DATA_DIR}}/data"
  - "{{ DATA_DIR }}/logs"
  - "{{ DATA_DIR }}/tmp"
  - "{{SOCKET_DIR}}"
  - "{{CONFIG_DIR}}"

- name: copy my.cnf to config_dir
  template: src={{ MYSQL_VERSION }}.cnf dest={{CONFIG_DIR}}/my{{MYSQL_PORT}}.cnf owner={{MYSQL_USER}} group={{MYSQL_USER}}


# 初始化配置
- name: mysql initialize
  shell: "{{BASE_DIR}}/bin/mysqld --defaults-file={{CONFIG_DIR}}/my{{MYSQL_PORT}}.cnf --basedir={{ BASE_DIR }} --datadir={{ DATA_DIR }}/data --user={{ MYSQL_USER }}  --initialize-insecure --lower_case_table_names={{ LOWER_CASE_TABLE_NAMES }}"
# 增加systemctl服务
- name: copy systemctl service file to server
  template: src="mysql.service" dest="/etc/systemd/system/mysql{{MYSQL_PORT}}.service" owner=root group=root

- name: start mysqld
  shell: "systemctl daemon-reload;systemctl start mysql{{MYSQL_PORT}}.service"

- name: 10. check mysql service start
  shell: ps -ef|grep {{MYSQL_PORT}} |grep "mysqld"|grep -v "grep"|wc -l
  register: check_mysqld_value

- debug: msg="mysqld service had exists,install success"
  when: check_mysqld_value.stdout|int > 0

# 增加mysql 环境变量
- name: add mysql env
  shell: "if [ `grep {{BASE_DIR}}/bin /etc/profile |wc -l` -eq 0 ]; then echo export PATH=$PATH:{{BASE_DIR}}/bin >> /etc/profile && source /etc/profile; else source /etc/profile; fi"